# Generated by Django 3.2.9 on 2021-11-21 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='содержание')),
                ('is_right', models.BooleanField(blank=True, default=False, verbose_name='правильный ответ')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='порядок вопроса в тесте')),
                ('title', models.CharField(max_length=200, verbose_name='вопрос')),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'verbose_name': 'Вопрос в тесте',
                'verbose_name_plural': 'Вопросы в тесте',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('complexity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сложность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание теста')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='дата и время создания')),
                ('categories', models.ManyToManyField(related_name='tests', to='quiz.Category', verbose_name='категории теста')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='время и дата прохождения теста')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='quiz.test', verbose_name='тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_tests', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Пройденный тест',
                'verbose_name_plural': 'Пройденные тесты',
            },
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='quiz.choice', verbose_name='вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='quiz.question', verbose_name='вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('user_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.usertest', verbose_name='пройденный тест')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на вопрос',
                'verbose_name_plural': 'Ответы пользователя на вопросы',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.test', verbose_name='тест'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='вопрос'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'order')},
        ),
    ]
