# Generated by Django 3.2.9 on 2021-11-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tests', to='quiz.Category', verbose_name='категории теста'),
        ),
    ]
