# Generated by Django 3.2.9 on 2021-11-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='порядок вопроса в тесте'),
        ),
    ]
