# Generated by Django 3.2.9 on 2021-11-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='порядок вопроса в тесте'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
