# Generated by Django 3.2.9 on 2021-11-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('complexity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='вопрос')),
                ('order', models.SmallIntegerField(verbose_name='порядок вопроса в тесте')),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizz.choice', verbose_name='ответ')),
                ('choices', models.ManyToManyField(related_name='questions', to='quizz.Choice', verbose_name='варианты ответов')),
                ('test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizz.test', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'Вопрос в тесте',
                'verbose_name_plural': 'Вопросы в тесте',
            },
        ),
        migrations.CreateModel(
            name='GradedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='quizz.test', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'Пройденный тест',
                'verbose_name_plural': 'Пройденные тесты',
            },
        ),
    ]
