# Generated by Django 3.2.9 on 2021-11-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
