# Generated by Django 3.2.9 on 2021-11-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_auto_20211114_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='порядок вопроса в тесте'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizz.test', verbose_name='тест'),
        ),
    ]
