# Generated by Django 3.2.9 on 2021-11-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_auto_20211114_1345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'order')},
        ),
    ]
