# Generated by Django 3.2.9 on 2021-11-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_alter_question_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order',), 'verbose_name': 'Вопрос в тесте', 'verbose_name_plural': 'Вопросы в тесте'},
        ),
    ]
