# Generated by Django 3.2.9 on 2021-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_alter_question_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GradedQuiz',
            new_name='GradedTest',
        ),
        migrations.AddField(
            model_name='test',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
