# Generated by Django 3.2.9 on 2021-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0006_auto_20211114_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='data',
        ),
        migrations.AddField(
            model_name='test',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
