# Generated by Django 3.2.9 on 2021-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0007_auto_20211114_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
